import classes from './_styles/page.module.scss';
import { TodoClientWrapper } from './_components/TodoClientWrapper';
import { Metadata } from 'next';

const baseUrl = process.env.NEXT_PUBLIC_SITE_URL;

export const metadata: Metadata = {
  title: 'My Todo list',
  description: 'Generated by Giorgos Eftychiou'
};

export const dynamic = 'force-dynamic';

type Todo = { id: number; text: string };
const fetchTodos = (): Promise<Array<Todo>> =>
  fetch(`${baseUrl}/api/todo`, { cache: 'no-store' }).then((res) => res.json());

export default async function TodoPage() {
  let todos = await fetchTodos();

  return (
    <div className={classes.ToDoPage}>
      <TodoClientWrapper todos={todos} />
    </div>
  );
}
