import classes from './_styles/projects.module.scss';
import { ProjectsClientWrapper } from './_components/ProjectsClientWrapper';

import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Giorgos Eftychiou Projects',
  description: 'Generated by me'
};

export default function Projects() {
  return (
    <div className={classes.page}>
      <ProjectsClientWrapper />
    </div>
  );
}
