import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../styles/globals.css';
import classes from './layout.module.scss';
import Link from 'next/link';
import { Nav } from '@/components/nav';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Giorgos Eftychiou',
  description: 'Generated by me'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={[inter.className, classes.body].join(' ')}>
        <header>
          <Nav />
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
