import { Metadata } from 'next';
import { ProjectsClientWrapper } from './_components/ProjectsClientWrapper';
import classes from './_styles/projects.module.scss';

export const metadata: Metadata = {
  title: 'Giorgos Eftychiou Projectss',
  description: 'Generated by me'
};

export default function Projects() {
  return (
    <div className={classes.page}>
      <ProjectsClientWrapper />
    </div>
  );
}
