import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../../styles/globals.css';
// import classes from './layout.module.scss';
// import Link from 'next/link';
import { Nav } from '@/shared/components/nav';

// const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Giorgos Eftychiouee',
  description: 'Generated by meee'
};

export default function ToDoLayout({ children }: { children: React.ReactNode }) {
  return <div style={{ marginTop: '60px' }}>{children}</div>;
}
