import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'My Todo list',
  description: 'Generated by Giorgos Eftychiou'
};

export default function ToDoLayout({ children }: { children: React.ReactNode }) {
  return <div style={{ marginTop: '60px' }}>{children}</div>;
}
